### ISSUE TITLE
Configuration merging issue on JRE 11

### ISSUE THREAD

**Issue by minettiandrea** [Insubric/box#184]
When using JRE 11 for some reason the merge of the config files behave differently from JRE 8, and ends up with a error creating the session manager

**Comment by minettiandrea** [comment]
Config merge still causes issues

**Comment by minettiandrea** [comment]
Still some errors on geotrellis

```
pureconfig.error.ConfigReaderException: Cannot convert configuration to a geotrellis.vector.conf.JtsConfig. Failures are:
  at the root:
    - (system properties) Key not found: 'geotrellis'.

	at pureconfig.ConfigSource.loadOrThrow(ConfigSource.scala:80)
	at pureconfig.ConfigSource.loadOrThrow$(ConfigSource.scala:77)
	at pureconfig.ConfigSource$$anon$2.loadOrThrow(ConfigSource.scala:335)
	at geotrellis.vector.conf.JtsConfig$.liftedTree1$1(JtsConfig.scala:46)
	at geotrellis.vector.conf.JtsConfig$.conf$lzycompute(JtsConfig.scala:45)
	at geotrellis.vector.conf.JtsConfig$.conf(JtsConfig.scala:45)
	at geotrellis.vector.conf.JtsConfig$.jtsConfigToClass(JtsConfig.scala:53)
	at geotrellis.vector.GeomFactory$.precisionModel$lzycompute(GeomFactory.scala:27)
	at geotrellis.vector.GeomFactory$.precisionModel(GeomFactory.scala:27)
	at geotrellis.vector.GeomFactory$.factory$lzycompute(GeomFactory.scala:30)
	at geotrellis.vector.GeomFactory$.factory(GeomFactory.scala:30)
	at geotrellis.vector.PointConstructors.apply(Point.scala:24)
	at geotrellis.vector.PointConstructors.apply$(Point.scala:23)
	at geotrellis.vector.Point$.apply(Point.scala:33)
	at geotrellis.vector.io.json.GeometryFormats.readPointCoords(GeometryFormats.scala:43)
	at geotrellis.vector.io.json.GeometryFormats.$anonfun$pointDecoder$3(GeometryFormats.scala:78)
	at scala.Option.map(Option.scala:242)
	at geotrellis.vector.io.json.GeometryFormats.$anonfun$pointDecoder$2(GeometryFormats.scala:78)
	at scala.util.Either.flatMap(Either.scala:352)
	at geotrellis.vector.io.json.GeometryFormats.$anonfun$pointDecoder$1(GeometryFormats.scala:77)
	at io.circe.Decoder$$anon$13.tryDecode(Decoder.scala:332)
	at io.circe.Decoder$$anon$13.apply(Decoder.scala:327)
	at io.circe.Json.as(Json.scala:107)
	at geotrellis.vector.io.json.GeometryFormats.$anonfun$geometryDecoder$2(GeometryFormats.scala:219)
	at scala.util.Either.flatMap(Either.scala:352)
	at geotrellis.vector.io.json.GeometryFormats.$anonfun$geometryDecoder$1(GeometryFormats.scala:217)
	at io.circe.Decoder$$anon$13.tryDecode(Decoder.scala:332)
	at io.circe.Decoder$$anon$13.apply(Decoder.scala:327)
	at io.circe.Decoder$$anon$39.tryDecode(Decoder.scala:930)
	at io.circe.ACursor.as(ACursor.scala:211)
	at io.circe.ACursor.get(ACursor.scala:218)
	at io.circe.ProductDecoders$$anon$3.apply(ProductDecoders.scala:36)
	at io.circe.Json.as(Json.scala:107)
	at ch.wsl.box.rest.logic.JSONTableActions.toM(JSONActions.scala:86)
	at ch.wsl.box.rest.logic.JSONTableActions.insert(JSONActions.scala:82)
	at ch.wsl.box.rest.logic.JSONTableActions.insert(JSONActions.scala:63)
	at ch.wsl.box.rest.logic.FormActions.insert(FormActions.scala:303)
	at ch.wsl.box.rest.routes.Form.$anonfun$route$50(Form.scala:352)
	at akka.http.scaladsl.server.directives.RouteDirectives.$anonfun$complete$1(RouteDirectives.scala:47)
	at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
	at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:68)
	at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
